favicon: null
cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.5275689
  brandStrength: 0.7272766572423279
  lightness: 0.5050125
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  rhythmicContrast: 0.641604
typography_spectrum: 0.9310430807527155
layout_spectrum: 0.3088973
analytics:
  twitter: null
  google: null
  facebook: null
name: AyeCloud
